#! /usr/bin/env sh

cp packages/bash42-001 /mnt/rastakware/sources
cp packages/bash42-002 /mnt/rastakware/sources
cp packages/bash42-003 /mnt/rastakware/sources
cp packages/bash42-004 /mnt/rastakware/sources
cp packages/bash42-005 /mnt/rastakware/sources
cp packages/bash42-006 /mnt/rastakware/sources
cp packages/bash42-007 /mnt/rastakware/sources
cp packages/bash42-008 /mnt/rastakware/sources
cp packages/bash42-009 /mnt/rastakware/sources
cp packages/bash42-010 /mnt/rastakware/sources
cp packages/bash42-011 /mnt/rastakware/sources
cp packages/bash42-012 /mnt/rastakware/sources
cp packages/bash42-013 /mnt/rastakware/sources
cp packages/bash42-014 /mnt/rastakware/sources
cp packages/bash42-015 /mnt/rastakware/sources
cp packages/bash42-016 /mnt/rastakware/sources
cp packages/bash42-017 /mnt/rastakware/sources
cp packages/bash42-018 /mnt/rastakware/sources
cp packages/bash42-019 /mnt/rastakware/sources
cp packages/bash42-020 /mnt/rastakware/sources
cp packages/bash42-021 /mnt/rastakware/sources
cp packages/bash42-022 /mnt/rastakware/sources
cp packages/bash42-023 /mnt/rastakware/sources
cp packages/bash42-024 /mnt/rastakware/sources
cp packages/bash42-025 /mnt/rastakware/sources
cp packages/bash42-026 /mnt/rastakware/sources
cp packages/bash42-027 /mnt/rastakware/sources
cp packages/bash42-028 /mnt/rastakware/sources
cp packages/bash42-029 /mnt/rastakware/sources
cp packages/bash42-030 /mnt/rastakware/sources
cp packages/bash42-031 /mnt/rastakware/sources
cp packages/bash42-032 /mnt/rastakware/sources
cp packages/bash42-033 /mnt/rastakware/sources
cp packages/bash42-034 /mnt/rastakware/sources
cp packages/bash42-035 /mnt/rastakware/sources
cp packages/bash42-036 /mnt/rastakware/sources
cp packages/bash42-037 /mnt/rastakware/sources
cp packages/bash42-038 /mnt/rastakware/sources
cp packages/bash42-039 /mnt/rastakware/sources
cp packages/bash42-040 /mnt/rastakware/sources
cp packages/bash42-041 /mnt/rastakware/sources
cp packages/bash42-042 /mnt/rastakware/sources
cp packages/bash42-043 /mnt/rastakware/sources
cp packages/bash42-044 /mnt/rastakware/sources
cp packages/bash42-045 /mnt/rastakware/sources
cp packages/bash-4.2.tar.gz /mnt/rastakware/sources
cp packages/binutils-2.23.2.tar.gz /mnt/rastakware/sources
cp packages/bzip2-1.0.6.tar.gz /mnt/rastakware/sources
cp packages/check-0.9.10.tar.gz /mnt/rastakware/sources
cp packages/coreutils-8.21.tar.xz /mnt/rastakware/sources
cp packages/dejagnu-1.5.1.tar.gz /mnt/rastakware/sources
cp packages/diffutils-3.3.tar.xz /mnt/rastakware/sources
cp packages/expect5.45.tar.gz /mnt/rastakware/sources
cp packages/findutils-4.4.2.tar.gz /mnt/rastakware/sources
cp packages/gawk-4.0.2.tar.xz /mnt/rastakware/sources
cp packages/gcc-4.8.0.tar.gz /mnt/rastakware/sources
cp packages/gettext-0.18.2.tar.gz /mnt/rastakware/sources
cp packages/glibc-2.17.tar.gz /mnt/rastakware/sources
cp packages/gmp-5.1.1.tar.bz2 /mnt/rastakware/sources
cp packages/grep-2.14.tar.xz /mnt/rastakware/sources
cp packages/gzip-1.5.tar.xz /mnt/rastakware/sources
cp packages/linux-3.9.tar.bz2 /mnt/rastakware/sources
cp packages/m4-1.4.16.tar.bz2 /mnt/rastakware/sources
cp packages/make-3.82.tar.gz /mnt/rastakware/sources
cp packages/mpc-1.0.1.tar.gz /mnt/rastakware/sources
cp packages/mpfr-3.1.2.tar.bz2 /mnt/rastakware/sources
cp packages/ncurses-5.9.tar.gz /mnt/rastakware/sources
cp packages/patch-2.7.1.tar.xz /mnt/rastakware/sources
cp packages/patch-3.9.1.bz2 /mnt/rastakware/sources
cp packages/perl-5.16.3.tar.gz /mnt/rastakware/sources
cp packages/readline-5.1.tar.gz /mnt/rastakware/sources
cp packages/sed-4.2.2.tar.gz /mnt/rastakware/sources
cp packages/tar-1.26.tar.xz /mnt/rastakware/sources
cp packages/tcl8.6.0-src.tar.gz /mnt/rastakware/sources
cp packages/xz-5.0.4.tar.xz /mnt/rastakware/sources
cp packages/zlib-1.2.8.tar.xz /mnt/rastakware/sources


